# 应用服务 WEB 访问端口
server:
  port: 8087
#Druid德鲁伊数据池
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver   #TODO 数据库未知
      url: jdbc:mysql://localhost:3306/db01?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456

#mp设置表
mybatis-plus:
  global-config:
    db-config:
      table-prefix: hadoop_    #TODO 数据库连接表未知,本地测试数据表hadoop_project
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
